apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-html
data:
  index.html: |
    <html>
      <head><title>AZURE FAILOVER</title></head>
      <body style="background:#064e3b;color:white;text-align:center;">
        <h1>ðŸŸ¢ AZURE â€“ FAILOVER ACTIVE</h1>
        <h2>AWS is DOWN â€“ Azure took over</h2>
      </body>
    </html>
