apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-html
data:
  index.html: |
    <html>
      <head><title>AWS PRIMARY</title></head>
      <body style="background:#0f172a;color:white;text-align:center;">
        <h1>ðŸš€ AWS â€“ PRIMARY</h1>
        <p>Users are served from AWS</p>
      </body>
    </html>
